version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: word_popularity_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - word_popularity

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: word_popularity_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - word_popularity

    # Symfony apache project container
    www:
        build: docker/php
        container_name: word_popularity_www
        ports:
            - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - word_popularity

networks:
    word_popularity:

volumes:
    db-data: